import { useEditor } from 'tldraw'
import { useEffect } from 'react'

export function RightClickPanHandler() {
const editor = useEditor()

useEffect(() => {
const container = editor.getContainer()
if (!container) return

let startX = 0
let startY = 0
let lastX = 0
let lastY = 0
let isPanning = false
let didDrag = false
let previousTool = 'select'

const DRAG_THRESHOLD = 5

function onPointerDown(e: PointerEvent) {
if (e.button !== 2) return

// Allow synthetic events (generated by us) to pass through
if (!e.isTrusted) return

// Block native right-click down
e.stopPropagation()
e.stopImmediatePropagation()
e.preventDefault()

startX = e.clientX
startY = e.clientY
lastX = e.clientX
lastY = e.clientY
isPanning = false
didDrag = false
}

function onPointerMove(e: PointerEvent) {
if (!e.isTrusted) return

if (!(e.buttons & 2)) {
if (isPanning) stopPanning()
return
}

const dx = e.clientX - startX
const dy = e.clientY - startY

if (!isPanning && Math.hypot(dx, dy) > DRAG_THRESHOLD) {
isPanning = true
didDrag = true
previousTool = editor.getCurrentToolId()
editor.setCurrentTool('hand')
editor.setCursor({ type: 'grabbing', rotation: 0 })
}

if (isPanning) {
e.stopPropagation()
e.stopImmediatePropagation()

const deltaX = e.clientX - lastX
const deltaY = e.clientY - lastY
lastX = e.clientX
lastY = e.clientY

const { x, y, z } = editor.getCamera()
editor.setCamera({
x: x + deltaX / z,
y: y + deltaY / z,
z,
})
}
}

function stopPanning() {
isPanning = false
editor.setCurrentTool(previousTool)
editor.setCursor({ type: 'default', rotation: 0 })
}

function onPointerUp(e: PointerEvent) {
if (e.button !== 2) return
if (!e.isTrusted) return

e.stopPropagation()
e.stopImmediatePropagation()
e.preventDefault()

if (isPanning) {
stopPanning()
return
}

// If we didn't drag, it's a click. 
// Dispatch synthetic events to trigger Tldraw's context menu.
// We dispatch to the original target so Tldraw can hit-test correctly.
const target = e.target as Element

const eventInit: PointerEventInit = {
bubbles: true,
cancelable: true,
view: window,
pointerId: e.pointerId,
pointerType: e.pointerType,
isPrimary: e.isPrimary,
button: 2,
buttons: 2, // Right button down
clientX: e.clientX,
clientY: e.clientY,
screenX: e.screenX,
screenY: e.screenY,
shiftKey: e.shiftKey,
ctrlKey: e.ctrlKey,
altKey: e.altKey,
metaKey: e.metaKey,
}

// 1. Simulate Pointer Down (so Tldraw knows we clicked)
target.dispatchEvent(new PointerEvent('pointerdown', eventInit))

// 2. Simulate Pointer Up (so Tldraw knows we released)
target.dispatchEvent(new PointerEvent('pointerup', { ...eventInit, buttons: 0 }))

// 3. Simulate Context Menu (so Tldraw opens the menu)
target.dispatchEvent(new MouseEvent('contextmenu', {
bubbles: true,
cancelable: true,
view: window,
button: 2,
buttons: 0,
clientX: e.clientX,
clientY: e.clientY,
screenX: e.screenX,
screenY: e.screenY,
shiftKey: e.shiftKey,
ctrlKey: e.ctrlKey,
altKey: e.altKey,
metaKey: e.metaKey,
}))
}

function onContextMenu(e: MouseEvent) {
// Allow synthetic events to pass
if (!e.isTrusted) return

// Block native context menu
e.preventDefault()
e.stopPropagation()
e.stopImmediatePropagation()
}

// Listen in CAPTURE phase to intercept native events before Tldraw
container.addEventListener('pointerdown', onPointerDown, true)
container.addEventListener('pointermove', onPointerMove, true)
container.addEventListener('pointerup', onPointerUp, true)
container.addEventListener('contextmenu', onContextMenu, true)

return () => {
container.removeEventListener('pointerdown', onPointerDown, true)
container.removeEventListener('pointermove', onPointerMove, true)
container.removeEventListener('pointerup', onPointerUp, true)
container.removeEventListener('contextmenu', onContextMenu, true)
}
}, [editor])

return null
}
